name: Java Check Style
on:
  push:
    branches:
      -master

jobs:
  java-check-style:
    runs_on: [ubuntu-latest]

    steps:
      - name: Git clone repo
      - uses: actions/checkout@v2

      - name: Set_version java
        uses: actions/setup-java@v2
        with:
          java-version: '17.0.2'

#      - name: Install java dependencies
#        run: |
#         установка зависимостей




